### ISSUE TITLE
first time login uncaught  error

### ISSUE THREAD

**Issue by leomaxi** [open-learning-exchange/myplanet#1101]
Realm leak
<img width="1657" alt="Screenshot 2019-08-30 at 11 49 55 AM" src="https://user-images.githubusercontent.com/2836302/64018689-a6d4d680-cb1c-11e9-962d-70f516807acc.png">

**Comment by rrijal53** [comment]
fixed

**Comment by leomaxi** [comment]
`09-02 10:09:21.167 3495-3546/org.ole.planet.myplanet E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa16d59a0
09-02 10:09:21.243 3495-3495/org.ole.planet.myplanet D/OLE: log: Destroyed 
09-02 10:09:21.299 3495-3495/org.ole.planet.myplanet E/ActivityThread: Activity org.ole.planet.myplanet.ui.sync.LoginActivity has leaked IntentReceiver io.realm.internal.network.NetworkStateReceiver@2d5d2eb that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity org.ole.planet.myplanet.ui.sync.LoginActivity has leaked IntentReceiver io.realm.internal.network.NetworkStateReceiver@2d5d2eb that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
        at io.realm.internal.SyncObjectServerFacade.init(SyncObjectServerFacade.java:70)
        at io.realm.Realm.init(Realm.java:260)
        at org.ole.planet.myplanet.datamanager.DatabaseService.getRealmInstance(DatabaseService.java:19)
        at org.ole.planet.myplanet.ui.sync.SyncActivity.onCreate(SyncActivity.java:62)
        at org.ole.planet.myplanet.ui.sync.LoginActivity.onCreate(LoginActivity.java:73)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-02 10:09:21.517 3495-3546/org.ole.planet.myplanet E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa16d5c20
`

**Comment by leomaxi** [comment]
`Another login error`
<img width="1359" alt="Screenshot 2019-09-02 at 12 18 27 PM" src="https://user-images.githubusercontent.com/2836302/64114302-2ad8c980-cd7c-11e9-9520-093b72b15061.png">

**Comment by rrijal53** [comment]
the other issue is already fixed, need to fix leaked issue only

**Comment by rrijal53** [comment]
done
