### ISSUE TITLE
RoboTest with small device failing with the following roboscript

### ISSUE THREAD

**Issue by ewhang5** [open-learning-exchange/myplanet#3791]
Ran a new workflow and got a new aab/apk for the 3645-illegalstateexception branch. Used the aab in a robotest with the small device, but it failed with the following error.
[OnBoardingActivity_robo_script (1).json](https://github.com/user-attachments/files/16131826/OnBoardingActivity_robo_script.1.json)

<img width="1254" alt="Screenshot 2024-07-08 at 9 57 02 AM" src="https://github.com/open-learning-exchange/myplanet/assets/59347000/4db120c5-b695-4285-abed-59d43d42058a">

**Comment by Okuro3499** [comment]
@ewhang5 copy and paste the error also

**Comment by ewhang5** [comment]
Error:
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{1eac363 VFED..... ........ 20,227-700,1120 #7f0a0468 app:id/recyclerView}, adapter:org.ole.planet.myplanet.ui.chat.ChatHistoryListAdapter@c80e836, layout:androidx.recyclerview.widget.LinearLayoutManager@72e2fdd, context:org.ole.planet.myplanet.ui.dashboard.DashboardActivity@ededdcf
     FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 10075
java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView{1eac363 VFED..... ........ 20,227-700,1120 #7f0a0468 app:id/recyclerView}, adapter:org.ole.planet.myplanet.ui.chat.ChatHistoryListAdapter@c80e836, layout:androidx.recyclerview.widget.LinearLayoutManager@72e2fdd, context:org.ole.planet.myplanet.ui.dashboard.DashboardActivity@ededdcf
	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3482)
	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:6071)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13219)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13209)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeChanged(RecyclerView.java:8153)
	at org.ole.planet.myplanet.ui.chat.ChatHistoryListAdapter.filter(ChatHistoryListAdapter.kt:61)
	at org.ole.planet.myplanet.ui.chat.ChatHistoryListFragment$onViewCreated$3.onTextChanged(ChatHistoryListFragment.kt:92)
	at android.widget.TextView.sendOnTextChanged(TextView.java:12349)
	at android.widget.TextView.handleTextChanged(TextView.java:12464)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:15839)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:305)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:49)
	at android.view.inputmethod.BaseInputConnection.replaceTextInternal(BaseInputConnection.java:1026)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:962)
	at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:743)
	at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:161)
	at android.view.inputmethod.RemoteInputConnectionImpl.lambda$setComposingText$25(RemoteInputConnectionImpl.java:785)
	at android.view.inputmethod.RemoteInputConnectionImpl.$r8$lambda$U35nSI1iZlwEe3OLFPCA1UPOEzs(Unknown Source:0)
	at android.view.inputmethod.RemoteInputConnectionImpl$$ExternalSyntheticLambda7.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by Okuro3499** [comment]
this is not the case currently
<img width="1181" alt="Screenshot 2024-10-07 at 17 15 40" src="https://github.com/user-attachments/assets/b5f7f621-b9da-4586-aeae-b14116278430">
