### ISSUE TITLE
InflateException

### ISSUE THREAD

**Issue by rlam20** [open-learning-exchange/myplanet#3969]
app crashes whenever trying to open settings

```FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 7499
android.view.InflateException: Binary XML file line #21: Error inflating class org.ole.planet.myplanet.views.RoundedListPreference
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:253)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380)
	at org.ole.planet.myplanet.ui.SettingActivity$SettingFragment.onCreatePreferences(SettingActivity.kt:76)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NoSuchMethodException: org.ole.planet.myplanet.views.RoundedListPreference.<init> [class android.content.Context, interface android.util.AttributeSet]
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:239)
	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281) 
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349) 
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161) 
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112) 
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217) 
	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380) 
	at org.ole.planet.myplanet.ui.SettingActivity$SettingFragment.onCreatePreferences(SettingActivity.kt:76) 
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161) 
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090) 
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475) 
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257) 
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899) 
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817) 
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760) 
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985) 
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895) 
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351) 
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251) 
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435) 
	at android.app.Activity.performStart(Activity.java:8024) 
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475) 
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:223) 
	at android.app.ActivityThread.main(ActivityThread.java:7656) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by rlam20** [comment]
seems to start on version 17.28
