### ISSUE TITLE
app crashes when you click on community leaders without login

### ISSUE THREAD

**Issue by deeppp15** [open-learning-exchange/myplanet#4379]
### Description

The app seems to be crashing/ freezing when you click on community leaders in community on the login page without logging in.

### Steps to recreate

- On login page
- Click on open ommunity
- click on any community leaders

### Video

https://github.com/user-attachments/assets/ba0d76cf-c7b2-4d10-b2fa-7711b14079c0

**Comment by Okuro3499** [comment]
paste the crash logs

**Comment by deeppp15** [comment]
2024-09-11 14:27:12.708 28627-28627 AndroidRuntime          org.ole.planet.myplanet              E  FATAL EXCEPTION: main
                                                                                                    Process: org.ole.planet.myplanet, PID: 28627
                                                                                                    java.lang.IllegalArgumentException: No view found for id 0x7f0a022b (org.ole.planet.myplanet:id/fragment_container) for fragment MemberDetailFragment{869f55b} (3351e04e-f7dd-479c-bc61-ab0a00d1e968 id=0x7f0a022b)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7073)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  java.lang.IllegalArgumentException: No view found for id 0x7f0a022b (org.ole.planet.myplanet:id/fragment_container) for fragment MemberDetailFragment{869f55b} (3351e04e-f7dd-479c-bc61-ab0a00d1e968 id=0x7f0a022b)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:514)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
2024-09-11 14:27:12.709 28627-28627 System.err              org.ole.planet.myplanet              W  	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at android.os.Handler.handleCallback(Handler.java:873)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at android.os.Looper.loop(Looper.java:214)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at android.app.ActivityThread.main(ActivityThread.java:7073)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at java.lang.reflect.Method.invoke(Native Method)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
2024-09-11 14:27:12.710 28627-28627 System.err              org.ole.planet.myplanet              W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2024-09-11 14:27:13.051 28627-29849 planet.myplane          org.ole.planet.myplanet              W  Thread attaching while runtime is shutting down: Binder:28627_5

**Comment by deeppp15** [comment]
closed because this error is not reproducable
