### ISSUE TITLE
app crashes when adding audio as resource

### ISSUE THREAD

**Issue by Kuljeet1998** [open-learning-exchange/myplanet#4470]
https://github.com/user-attachments/assets/43f93fbd-e540-4ace-b437-c564e6aceb85

**Comment by Okuro3499** [comment]
@Kuljeet1998 copy and add crash log

**Comment by Kuljeet1998** [comment]
`FATAL EXCEPTION: main
                                                                                                    Process: org.ole.planet.myplanet, PID: 9013
                                                                                                    java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;)V in class Landroid/media/MediaRecorder; or its super classes (declaration of 'android.media.MediaRecorder' appears in /system/framework/framework.jar!classes2.dex)
                                                                                                    	at org.ole.planet.myplanet.service.AudioRecorderService.startRecording(AudioRecorderService.kt:33)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment.showAudioRecordAlert$lambda$9(AddResourceFragment.kt:118)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment.$r8$lambda$QjcXgdQHzp6G-3tC7ZLh3ED4E9w(Unknown Source:0)
                                                                                                    	at org.ole.planet.myplanet.ui.resources.AddResourceFragment$$ExternalSyntheticLambda7.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7520)
                                                                                                    	at android.view.View.performClickInternal(View.java:7489)
                                                                                                    	at android.view.View.access$3600(View.java:826)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28555)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8068)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

**Comment by Okuro3499** [comment]
@Kuljeet1998 what are the specs of the device it's crashing on?
